<!DOCTYPE HTML>
<html lang="en">
<meta charset="utf-8">
<title>YNE 🏠</title>
<meta name=description content="writing minimalist software since '91">
<meta name=viewport content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta name="color-scheme" content="dark">
<link rel="icon" href="data:image/svg+xml;utf8,include(./logo.svg)" type="image/svg+xml">

include(./home.md.html)
include(./projects.md.html)
include(./music.md.html)
include(./photos.md.html)

<hr>

Generated by <a href="https://github.com/yne/yne.github.io/blob/master/Makefile">Make+M4+jq</a>
